### PR TITLE
Shader interface matching rework to fix #2136

### LINKED ISSUE #2136: Shouldn't TIntermediate::mergeLinkerObjects be matching blocks by block-name, not instance-name
Currently if you have two blocks with different layouts in two compilation units, with the same block-name, but different instance-name, the validator does not fail.
[SameBlockDiffInstance2.txt](https://github.com/KhronosGroup/glslang/files/4351610/SameBlockDiffInstance2.txt)
[SameBlockDiffInstance1.txt](https://github.com/KhronosGroup/glslang/files/4351611/SameBlockDiffInstance1.txt)
I think this should fail, no?

Conversely, if you have 2+ anonymous blocks (legal ones) it will fail if they are declared in different order, since it will be trying to match up by anon@0, naming, not the block names.

[MultiAnonBlocks1.txt](https://github.com/KhronosGroup/glslang/files/4351633/MultiAnonBlocks1.txt)
[MultiAnonBlocks2.txt](https://github.com/KhronosGroup/glslang/files/4351634/MultiAnonBlocks2.txt)

Seems like the root issue is that TIntermediate::mergeLinkerObjects is matching up the blocks by instance name and not block name.

Working on a patch, but let me know if I'm off base. Thanks

### PR DESCRIPTION
**Pull request by mbechard**

### CODE REVIEW

File: glslang/Include/Types.h [hunk 1]
```diff
@@ -1616,6 +1628,24 @@ class TType {
...
+            return EsiNone;
+        case EvqVaryingIn:
+            return EsiInput;
+		case EvqVaryingOut:
+            return EsiOutput;
+        case EvqUniform:
+            return EsiUniform;
+        case EvqBuffer:
+            return EsiBuffer;
+		}
```
Comment (johnkslang) [inline glslang/Include/Types.h]: Something happening here with tabs.  Project is all spaces.

File: glslang/Include/Types.h [hunk 2]
```diff
@@ -473,6 +473,18 @@ enum TInterlockOrdering {
     EioCount,
 };
 
+enum TShaderInterface
+{
+    EsiUniform = 0,
```
Comment (johnkslang) [inline glslang/Include/Types.h]: Shouldn't we have just 3 interfaces?  In, out, and uniform?

Comment (mbechard) [reply glslang/Include/Types.h]: Good question. I just checked and on Windows neither the Nvidia nor the Intel compiler allow for duplicated block names between uniform blocks and buffer blocks, however the spec states:

> A shader interface is defined to be one of these:
> • All the uniform variables and uniform blocks declared in a program. This spans all compilation
> units linked together within one program.
> • All the buffer blocks declared in a program.
> • The boundary between adjacent programmable pipeline stages: This spans all the outputs
> declared in all compilation units of the first stage and all the inputs declared in all compilation
> units of the second stage. Note that for the purposes of this definition, the fragment shader and
> the preceding shader are considered to have a shared boundary even though in practice, all
> values passed to the fragment shader first pass through the rasterizer and interpolator.

Which to me means buffers are a different interface than uniform blocks.

File: glslang/Include/Types.h (hunk 1 above)
Comment (mbechard) [reply glslang/Include/Types.h]: Sorry, the clang-format is catching most of these but I think one action in vim I'm doing is still inserting tabs. I'll push a fix

File: glslang/Include/Types.h (hunk 2 above)
Comment (johnkslang) [reply glslang/Include/Types.h:478]: I think experts in this space commonly consider buffer and uniform to be in the same space, which agrees with your driver experience, so let's go with that.  It will certainly be more portable.

Comment (mbechard) [reply glslang/Include/Types.h:478]: Ok sounds good. I'll make an issue report over on the GLSL spec repo since I feel this can be more clearly stated then.

Comment (mbechard) [reply glslang/Include/Types.h:479]: Pushed
