### PR TITLE
Fix interpolant ES error

### LINKED ISSUE #3277: interpolate struct member
Acoording es32 spec:
For all of the interpolation functions, interpolant must be an input variable or an element of an input
variable declared as an array.
glcts.exe--deqp-case=dEQP-GLES31.functional.shaders.multisample_interpolation.interpolate_at_sample.negative.interpolate_struct_member

Glslang need report error for following shader
#version 320 es
struct S
{
	highp float a;
	highp float b;
};
in S v_var;
layout(location = 0) out mediump vec4 fragColor;
void main (void)
{
	fragColor = vec4(interpolateAtSample(v_var.a, 0)); // <interpolant> is not an input variable (just a member of)
}

### PR DESCRIPTION
**Pull request by ncesario-lunarg**
The restriction of no swizzling and no struct fields as an interpolant were not being checked when using the ES profile.

Fixes #3277.

### CODE REVIEW

File: glslang/MachineIndependent/ParseHelper.cpp [hunk 1]
```diff
@@ -2536,10 +2536,53 @@ void TParseContext::builtInOpCheck(const TSourceLoc& loc, const TFunction& fnCan
...
+            const bool esProfile = isEsProfile();
+            const bool swizzleOkay = !esProfile && (version >= 440);
+
+            std::string interpolantErrorMsg = "first argument must be an interpolant, or interpolant-array element";
+            bool isValid = true; // Assume that the interpolant is valid until we find a condition making it invalid
+            bool isIn = false;   // Checks whether or not the interpolant is a shader input
+            bool structAccessOp = false; // Whether or not the previous node in the chain is a struct accessor
+            TIntermediate::traverseLValueBase(
+                arg0, swizzleOkay, false,
+                [&isValid, &isIn, &interpolantErrorMsg, esProfile, &structAccessOp](const TIntermNode& n) {
```
Comment (ncesario-lunarg) [inline glslang/MachineIndependent/ParseHelper.cpp:2548]: @arcady-lunarg @jeremy-lunarg I went back and forth with creating a dedicated function to fix this or a more generic function to traverse. Let me know what you prefer style-wise.

File: glslang/MachineIndependent/localintermediate.h [hunk 2]
```diff
@@ -43,11 +43,12 @@
...
 
-#include <string>
-#include <vector>
 #include <algorithm>
-#include <set>
 #include <array>
+#include <functional>
+#include <set>
+#include <string>
+#include <vector>
```
Comment (ncesario-lunarg) [inline glslang/MachineIndependent/localintermediate.h:51]: The only actual addition here is `<functional>`. `clang-format` put them in alphabetical order.

File: glslang/MachineIndependent/ParseHelper.cpp (hunk 1 above)
Comment (arcady-lunarg) [reply glslang/MachineIndependent/ParseHelper.cpp:2548]: I think it's better to keep it inline but I also would prefer a brief comment explaining what this is doing.

File: glslang/MachineIndependent/localintermediate.h [hunk 3]
```diff
@@ -573,6 +574,8 @@ class TIntermediate {
 
     // Tree ops
     static const TIntermTyped* findLValueBase(const TIntermTyped*, bool swizzleOkay , bool BufferReferenceOk = false);
+    static const TIntermTyped* traverseLValueBase(const TIntermTyped*, bool swizzleOkay, bool bufferReferenceOk = false,
```
Comment (arcady-lunarg) [inline glslang/MachineIndependent/localintermediate.h:577]: I'm a bit confused as to why a) this returns a value since your one use of it doesn't consume the return value at all and b) why proc has a default value. Were you trying to combine `findLValueBase` and `traverseLValueBase` and just didn't finish the job? It might not be a bad idea to combine those two btw since the traversal code is annoying and would be best written only once.

**Review by arcady-lunarg — CHANGES_REQUESTED** [review]
A couple comments on some details but the overall approach is good. Thanks for adding some pretty comprehensive tests.

File: glslang/MachineIndependent/localintermediate.h (hunk 3 above)
Comment (ncesario-lunarg) [reply glslang/MachineIndependent/localintermediate.h:577]: Yes, that was my original intent, but felt it was a little messy and so I wanted to get some feedback first. I would also prefer these to be combined, but wasn't sure what the preference would be for the generic traversal code. If you're ok with the generic approach, I'll combine them.

Comment (arcady-lunarg) [reply glslang/MachineIndependent/localintermediate.h:577]: I think it's cleaner this way, the complicated traversal logic exists only once.

File: glslang/MachineIndependent/localintermediate.h [hunk 4]
```diff
@@ -573,6 +574,8 @@ class TIntermediate {
 
     // Tree ops
     static const TIntermTyped* findLValueBase(const TIntermTyped*, bool swizzleOkay , bool BufferReferenceOk = false);
```
Comment (arcady-lunarg) [inline glslang/MachineIndependent/localintermediate.h:576]: I think you need to delete this because the function doesn't exist.

**Review by arcady-lunarg — CHANGES_REQUESTED** [review]
Thanks, I think it's cleaner like this, one small nit left to address and this can be merged.

File: glslang/MachineIndependent/localintermediate.h (hunk 4 above)
Comment (ncesario-lunarg) [reply glslang/MachineIndependent/localintermediate.h:576]: Ah, yep, thanks for catching that!

**Review by arcady-lunarg — APPROVED** [review]
