### PR TITLE
Perform update_precision on constructors and converts

### LINKED ISSUE #2740: Precision is incorrectly propagated to function call arguments
glslang has the following code in `TIntermTyped::propagatePrecision`:

```c
    TIntermAggregate* aggregateNode = getAsAggregate();
    if (aggregateNode) {
        TIntermSequence operands = aggregateNode->getSequence();
        for (unsigned int i = 0; i < operands.size(); ++i) {
            TIntermTyped* typedNode = operands[i]->getAsTyped();
            if (! typedNode)
                break;
            typedNode->propagatePrecision(newPrecision);
        }

        return;
    }
```

So given `f(a, b, c)` with the result precision being `mediump`, it would apply `mediump` to every argument of this function (that doesn't already have a precision). This includes any argument that is a constructor (because per spec constructors don't have a precision). This is not correct. For example, in ANGLE I discovered that given `texture(mediump_sampler, vec3(coords));`, `coords_expression` was being evaluated at `mediump` even though it contained only `highp` variables (inside constructors). The same expression given a `highp` sampler would evaluate the coordinates in `highp`!

### PR DESCRIPTION
**Pull request by greg-lunarg**
Fixes #2740

### CODE REVIEW

File: glslang/MachineIndependent/ParseHelper.cpp [hunk 1]
```diff
@@ -7691,7 +7691,13 @@ TIntermTyped* TParseContext::addConstructor(const TSourceLoc& loc, TIntermNode*
             return nullptr;
     }
 
-    return intermediate.setAggregateOperator(aggrNode, op, type, loc);
+    TIntermTyped *ret_node = intermediate.setAggregateOperator(aggrNode, op, type, loc);
+
+    TIntermAggregate *agg_node = ret_node->getAsAggregate();
+    if (agg_node && agg_node->isVector())
```
Comment (ShabbyX) [inline glslang/MachineIndependent/ParseHelper.cpp:7697]: Why only vectors?

Comment (greg-lunarg) [reply glslang/MachineIndependent/ParseHelper.cpp:7697]: Yes, matrix and array should also be handled. I just did vector for the moment to more quickly fix your problem and get on to a couple other more pressing issues. I will open an issue to track this.
