### PR TITLE
Fix spirv backcompat

### LINKED ISSUE #3882: The commit "ci: Add find_package testing" breaks installing libSPIRV.so
The commit 104bd85d990155f04f050972374a3502b4631830 stops building and installing libSPIRV.so.

My setup is as follows and with external SPIRV-Tools,

```
mkdir build
cd    build

cmake -D CMAKE_INSTALL_PREFIX=/usr     \
      -D CMAKE_BUILD_TYPE=Release      \
      -D BUILD_SHARED_LIBS=ON          \
      -D ALLOW_EXTERNAL_SPIRV_TOOLS=ON \
      -Wno-dev -G Ninja ..            &&
ninja

sudo ninja install
```

e66176c3f685b14dfa83882329e5d02f4e027c9b is fine.

### PR DESCRIPTION
**Pull request by jpr42**
closes #3882

### CODE REVIEW

File: glslang/stub.cpp [hunk 1]
```diff
@@ -32,6 +32,20 @@
...
-// deprecated libraries which have been integrated into the main glslang
-// library. It should be deleted once the stub libraries are fully removed.
+#ifdef GLSLANG_IS_SHARED_LIBRARY
+#ifdef _WIN32
+#ifdef GLSLANG_EXPORTING
+#define STUB_EXPORT __declspec(dllexport)
+#else
+#define STUB_EXPORT __declspec(dllimport)
+#endif
+#endif
```
Comment (jpr42) [inline glslang/stub.cpp:42]: NOTE: Windows is the only platform with this weird requirement. So I didn't add exporting logic for other platforms to highlight this is really only to address this niche issue.

**Review by jeremy-lunarg — APPROVED** [review]
LGTM. Thanks for the fix.
