### PR TITLE
Avoid generating 8/16-bit constants when 8/16-bit arithmetic extensions aren't enabled

### LINKED ISSUE #1828: 8- and 16-bit storage extensions generate invalid constants
#1827 updates SPIRV-Tools to include validation of 8- and 16-bit storage extensions. The validator flags glslang's constant generation for these tests as generating constants of the incorrect types. It should instead generate 32-bit type constants and use conversion instructions.

### PR DESCRIPTION
**Pull request by jeffbolznv**
Fixes #1828.

This changes how constructors are implemented to construct a 32-bit type and then convert to the 8/16-bit type.

I'm aware of one hole with this. It makes it an error to do something like "const int x = int(int_8(1));" that would have folded away the intermediate 8-bit constant, because the intermediate result won't be folded. But I can live with that...

### CODE REVIEW

**Comment by jeffbolznv** [comment]
@alan-baker FYI

**Comment by alan-baker** [comment]
I think you need to undo the test update I made when pulling in the new SPIRV-Tools.

**Comment by jeffbolznv** [comment]
Ah, !1827 got merged after I branched. I've rebased and regenerated.

File: glslang/Include/intermediate.h [hunk 1]
```diff
@@ -657,6 +657,15 @@ enum TOperator {
     EOpConstructVec2,
     EOpConstructVec3,
     EOpConstructVec4,
+    EOpConstructMat2x2,
```
Comment (johnkslang) [inline glslang/Include/intermediate.h]: Is this being done to support math on the op enum-value itself?  If so, I think we need a healthy comment saying so.

(On a side branch, I was rearranging these for a different purpose, and it will be very confusing debugging if the conflict is resolved incorrectly.)

**Comment by johnkslang** [comment]
It is comforting to see the validation errors go away, so it's a nice order to do things in.

File: glslang/Include/intermediate.h (hunk 1 above)
Comment (jeffbolznv) [reply glslang/Include/intermediate.h]: I've added a comment. I'm also willing to add a function with a big switch statement to convert, if you'd rather.

Comment (johnkslang) [reply glslang/Include/intermediate.h]: Given that we have some "guard" regions for fast checking, I think it is okay this way.

I was kind of wondering if the C++ optimizer would see the reduction in the switch statement, but I think this is okay.  Thanks.
